for check1
ok-technopolis-autumn-2019/Pavel_Panichkin pull request #1
Opened 2019-10-13 17:25 UTC by ya111

2019-10-13 18:01 UTC, fromanywhere requested changes

2019-10-13 18:01 UTC, fromanywhere commented on page.html
>  <head>
Немного не хватает внимания к accessibility — часть проблем закрывается тем, что браузер сам прочтет текст с кнопки или placeholder, но на чекбоксах, радиокнопках, кнопках удаления, конечно, нужны aria-label (это как минимум, можно еще aria roles-ами разметку расписать, но это допустим уже ладно)

2019-10-13 18:01 UTC, fromanywhere commented on page.html
>  		<div class = "todosButtons">
Во-первых, следовало бы увеличить область пользовательского клика с использованием слинкованного с радиокнопкой <label. Во-вторых, было бы неплохо соблюдать выбранный Вами способ логического кодирования имен классов (я не навязываю сейчас свой) — где-то camelCase, где-то "delete-button". Ну и если про логику в разметке, то хотелось бы более точного именования «компонентов» по их назначению. То есть под todosButtons я могу представить себе вообще всё что угодно. А если у меня потом появятся еще какие-то кнопки в макете в другом месте, как это будет выглядеть, todosButtons2? С неймингом всегда непросто, но попробовать стоит

2019-10-13 18:01 UTC, fromanywhere commented on page.html
> +			<input type="radio" name="group1" class = "buttonShow"><span>Active</span></input>
Вообще конечно так-то value у радиокнопок должен быть, хоть оно здесь и не так очевидно

2019-10-13 18:01 UTC, fromanywhere commented on page.html
>  		<div class = "todosButtons">
О, статус о количестве выполненных тудушек потерялся

2019-10-13 18:01 UTC, fromanywhere commented on page.html
> +			<input type="radio" name="group1" class = "buttonShow"><span>Completed</span></input>
Следовало бы выделить фильтр задач в отдельный «компонент», а значит, и структура в этом месте будет не плоским списком, а сгруппированной в три части — первая под статус, вторая под фильтр, третья под кнопку

2019-10-13 18:01 UTC, fromanywhere commented on page.html
>  			<div class = "todosListAddItem">
Атрибут size ниже избыточен

2019-10-13 18:01 UTC, fromanywhere commented on page.html
>  			<button class = "button">Clear completed</button>
Цепляться на ревью к форматированию — дело последнее, но я всё-таки напомню, что стиль должен быть одним, и даже если у вас не Prettier, то за пробелами бы последить

2019-10-13 18:01 UTC, fromanywhere commented on styles/default.css
> +input[type="checkbox"]:checked+span {
Несмотря на то, что этого файла в pr быть не должно, я покомментирую на будущее. Технически в этом селекторе ошибки нет, но лучше, если стилизацию цеплять за имена классов, потому что как только мы выходим за пределы песочницы в какой-то сколько бы то ни было настоящий проект, такого рода правило зааффектит и то что нужно, и что не нужно — слишком общее правило

2019-10-13 18:01 UTC, fromanywhere commented on styles/default.css
> +* {
Свойства, связанные с текстом, наследуются, поэтому * не нужен, достаточно на html или body

2019-10-13 18:01 UTC, fromanywhere commented on styles/default.css
> +    letter-spacing: -2.5px;
не надо так, пользователи с других операционных систем, у которых не будет Гельветики и Ариала, вас потом будут вспоминать разными словами, потом что им ОС подставит какой-нибудь такой шрифт, о котором Вы даже не знаете, и как он там рассчитает letter-spacing, никто не знает

2019-10-13 18:01 UTC, fromanywhere commented on styles/default.css
> +	align: center;
align? нет такого css-свойства

2019-10-13 19:21 UTC, ya111 commented on styles/default.css
> +input[type="checkbox"]:checked+span {
В таком случае правки по css вносить в эту ветку не буду, но всё будет исправлено

2019-10-13 19:23 UTC, ya111 commented on page.html
>  		<div class = "todosButtons">
Надеюсь, Вы не против lowerCamelCase'а, но без проблем могу переформатировать к виду lisp-case'у

2019-10-14 09:15 UTC, fromanywhere approved these changes

2019-10-14 09:16 UTC, merged