Css branch
ok-technopolis-autumn-2019/Pavel_Panichkin pull request #2
Opened 2019-10-13 21:20 UTC by ya111

css пока так, планы озвучены в коммите

2019-10-14 13:00 UTC, ya111 commented
в ближайшее время разделю css'ки и сделаю, чтобы delete всплывал при наведении на итем, а не кнопку

2019-10-15 09:46 UTC, fromanywhere requested changes

2019-10-15 09:46 UTC, fromanywhere commented on styles/project/mainLayout.css
> +    position: fixed;
но зачем здесь fixed? Какая задача решается?

2019-10-15 09:46 UTC, fromanywhere commented on styles/project/todosList.css
> +    line-height: 1.5
;

2019-10-15 09:46 UTC, fromanywhere commented on styles/project/todosList.css
> +    display: flex;
Вообще после того, как оно стало display: flex, маркеры больше беспокоить не должны

2019-10-15 09:46 UTC, fromanywhere commented on styles/project/todosList.css
> +    float: right;
Где-то тут в любом случае ошибка. Если бы выше не было опечатки и флекс бы сработал, то флоат не имел бы смысла. А если бы флекса на родителе не было, то где клеарфикс?

2019-10-15 09:46 UTC, fromanywhere commented on styles/project/todosList.css
> +	content: '✔';
Здесь, конечно, должна быть картинка

2019-10-15 09:46 UTC, fromanywhere commented on styles/project/todosList.css
> +input[type="checkbox"]:checked:before {
Псевдоэлементы на чекбоксе будут работать только в вебкитах — так не пойдет

2019-10-15 09:46 UTC, fromanywhere commented on styles/project/todosList.css
> +input[type="checkbox"]:checked+span {
Селектор по тегу широковат, лучше по классу

2019-10-15 09:46 UTC, fromanywhere commented on styles/project/todosToolbar.css
> +}
Как-то ему плохо на узком экране, да и форма добавления нового элемента хромает. Кстати, откуда там появилась кнопка add? в макете её нет

2019-10-15 14:24 UTC, ya111 commented on styles/project/mainLayout.css
> +    position: fixed;
Решалась проблема того, что без фиксированной позиции, страницы была шире допустимого. починил, убрав margin.

2019-10-15 14:26 UTC, ya111 commented on styles/project/todosList.css
> +    line-height: 1.5
убрал в принципе

2019-10-15 14:31 UTC, ya111 commented on styles/project/todosList.css
> +	content: '✔';
ошибка найдена

2019-10-15 14:31 UTC, ya111 commented on styles/project/todosList.css
> +    float: right;
ошибка найдена

2019-10-15 15:24 UTC, ya111 commented on styles/project/todosList.css
> +input[type="checkbox"]:checked:before {
Правильно ли я понимаю, что мне нужно отказаться от формулировки :before? Можно ли использовать в todosListItem :first-child?

2019-10-15 15:54 UTC, fromanywhere commented on styles/project/todosList.css
> +input[type="checkbox"]:checked:before {
Тут есть два подхода — один правильный, другой работающий. Правильный — это сделать «компонент», который будет иметь обертку, чекбокс и декоративный элемент внутри, и декоративный элемент будет честным узлом, а не псевдоэлементом, а его отображение будет работать через + селектор. К сожалению, мне не удалось найти решение, как в таком случае заодно еще и зачеркивать текст выбранной задачи. Поэтому есть еще второе решение, работающее. Оно точно такое же, только нет явно выделенного компонента, а чекбокс, декоративный элемент и текст лежат на одном уровне вложенности. Тогда изображение на декоративный элемент всё еще можно будет повесить через :checked + .element, а перечеркнуть текст с помощью :checked ~ .text

2019-10-15 16:50 UTC, ya111 commented on styles/project/todosList.css
> +input[type="checkbox"]:checked:before {
Решил не отказываться от таких чекбоксов. В хроме/сафари/фаерфоксе всё работает без проблем, а для IE/EDGE сделал костылёк (см. коммит f9b84ec). Или такое не приветствуется?

2019-10-15 17:26 UTC, ya111 commented on styles/project/todosList.css
> +input[type="checkbox"]:checked:before {
в фаерфоксе он тоже не поддерживается, понял, буду менять

2019-10-16 20:42 UTC, ya111 commented
знаю, что надо починить текст (чтобы переходил на новую строку, а не вправо), добавить видимость табуляции для пользователя, установить минимальную ширину

2019-10-20 23:29 UTC, fromanywhere commented
> знаю, что надо починить текст (чтобы переходил на новую строку, а не вправо), добавить видимость табуляции для пользователя, установить минимальную ширину

еще графику ретиновую, нейминг по bem и вот в этом месте с геометрией совсем плохо 
![image](https://user-images.githubusercontent.com/1042969/67168204-91f12280-f3aa-11e9-8d0a-21b89c6736a6.png)

2019-10-27 11:11 UTC, ya111 commented
ретина, табуляция, тени отсутствуют

2019-10-27 17:02 UTC, ya111 commented
Если аутлайн не убран, то красиво подсвечивается, но такое не работает в опере. Если ли смысл делать :focus на все кнопки и прописывать свой цвет бордера?

2019-10-27 21:57 UTC, fromanywhere commented
> Если аутлайн не убран, то красиво подсвечивается, но такое не работает в опере. Если ли смысл делать :focus на все кнопки и прописывать свой цвет бордера?
> 
> UPD: в сафари тоже не отображается(((

Не очень понял вопрос, у меня в сафари вроде работает. Я бы дополнительно бордер на фокус в рамках этого макета не прописывал, а так по жизни всякое бывает

2019-10-27 21:59 UTC, fromanywhere approved these changes

2019-10-27 21:59 UTC, fromanywhere commented
Всё это конечно очень далеко от макета, но я оценил приложенные усилия

2019-10-28 07:30 UTC, merged